name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r mal/requirements.txt

      - name: Run tests
        working-directory: mal
        run: pytest tests

      - name: Build ML service artifact
        working-directory: mal
        run: scripts/build_zip.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ml_service_artifact
          path: mal/build/ml_service.zip